blank_issues_enabled: true
contact_links:
  - name: 💬 Questions & Discussion
    url: https://github.com/SeeRay11/openflow/discussions
    about: For support, troubleshooting, how-to questions, and discussion about OpenFlow.
